import type { Tag } from './schema'
export const tags: Tag[] = [
  { id: 'collage', name: '拼贴', dimension: 'visual' },
  { id: 'lettering', name: '字形', dimension: 'visual' },
  { id: 'halftone', name: '网点', dimension: 'visual' },
  { id: 'rational', name: '理性', dimension: 'mood' },
  { id: 'futuristic', name: '未来感', dimension: 'mood' },
  { id: 'ink', name: '水墨', dimension: 'visual' },
  { id: 'translucent', name: '通透', dimension: 'visual' },
  { id: 'purple', name: '紫色', dimension: 'color', color: '#8478CF' },
  { id: 'calm', name: '沉静', dimension: 'mood' },
  { id: 'warm', name: '温暖', dimension: 'mood' },
  { id: 'elegant', name: '优雅', dimension: 'mood' },
  { id: 'luxurious', name: '华丽', dimension: 'mood' },
  { id: 'nostalgic', name: '怀旧', dimension: 'mood' },
  { id: 'lively', name: '活泼', dimension: 'mood' },
  { id: 'free', name: '自由', dimension: 'mood' },
  { id: 'mysterious', name: '神秘', dimension: 'mood' },
  { id: 'wood', name: '木质', dimension: 'visual' },
  { id: 'geometry', name: '几何', dimension: 'visual' },
  { id: 'textile', name: '织物', dimension: 'visual' },
  { id: 'metal', name: '金属', dimension: 'visual' },
  { id: 'neon', name: '霓虹', dimension: 'visual' },
  { id: 'organic', name: '自然肌理', dimension: 'visual' },
  { id: 'contrast', name: '高对比', dimension: 'visual' },
  { id: 'muted', name: '低饱和', dimension: 'visual' },
  { id: 'blue', name: '蓝色', dimension: 'color', color: '#36546b' },
  { id: 'red', name: '红色', dimension: 'color', color: '#823b42' },
  { id: 'green', name: '绿色', dimension: 'color', color: '#53634b' },
  { id: 'brown', name: '棕色', dimension: 'color', color: '#976b49' },
  { id: 'cream', name: '米白', dimension: 'color', color: '#e8ddc8' },
  { id: 'gold', name: '金色', dimension: 'color', color: '#b99a60' },
  { id: 'orange', name: '橙色', dimension: 'color', color: '#b76b43' },
  { id: 'black', name: '黑灰', dimension: 'color', color: '#444342' },
  { id: 'poster', name: '海报', dimension: 'usage' },
  { id: 'slides', name: '演示文稿', dimension: 'usage' },
  { id: 'brand', name: '品牌视觉', dimension: 'usage' },
]
